workspace 'GTUICatalog.xcworkspace'
#install! 'cocoapods', :deterministic_uuids => false


target 'GTUICatalog' do
  platform :ios, '8.0'
  project 'GTUICatalog.xcodeproj'
  inhibit_all_warnings
  use_frameworks!

  pod 'GTCatalog'
  pod 'GTUIKitExamples', :path => '../'
  pod 'GTUIKit', :path => '../'
  pod 'Masonry'

end

