workspace 'GTUICatalog.xcworkspace'


target 'GTUICatalog' do
  platform :ios, '8.0'
  project 'GTUICatalog.xcodeproj'
  use_frameworks!

  pod 'GTCatalog'
  pod 'GTUIKitExamples', :path => '../'
  pod 'GTUIKit', :path => '../'
  pod 'Masonry'

end

